# Generated by Django 4.1.5 on 2023-07-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('specific_description', models.TextField()),
                ('content', models.TextField()),
                ('property_type', models.CharField(choices=[('Hostel', 'Hostel'), ('Apartment', 'Apartment'), ('Flat', 'Flat'), ('Building', 'Building'), ('House', 'House'), ('Villa', 'Villa'), ('Office', 'Office')], max_length=50)),
                ('selling_type', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('total_rooms', models.PositiveIntegerField()),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('image1', models.ImageField(upload_to='property_images/')),
                ('image2', models.ImageField(upload_to='property_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold Out', 'Sold Out')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhome.user')),
            ],
        ),
    ]
