# Generated by Django 4.1.5 on 2023-07-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0003_submitproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent')], default='User', max_length=50),
        ),
    ]
